### ISSUE TITLE
Notification when a limit is reached

### ISSUE THREAD

**Issue by cyMarvin** [brotkrueml/typo3-form-rate-limit#1]
Since I didn't find anything about this in the documentation or the code, I'm posting this as a feature request.

I would like the extension to send a notification (e.g. to a given email address) when a limit is reached or dispatch an event containing the IP address that caused it, so that it can be processed and a log entry created or a notification sent (similar to EXT:powermail's spam notification).

Is this already possible or planned in the future?

**Comment by brotkrueml** [comment]
@cyMarvin I assume, you are using the limit to allow only, for example, 50 submissions for a form? Or do you have another scenario?

For now, this is not provided, as you suggest, dispatching a PSR-14 event may be the best solution to allow integrators/developers to react on reaching a limit individually.

**Comment by brotkrueml** [comment]
Available in v1.2.0.

**Comment by cyMarvin** [comment]
@brotkrueml Sorry for not replying. Seems like I missed the notification. =/
Thank you for implementing this event!
The reason for my request was to receive the client IP addresses that trigger the rate limit regularly to blacklist them in my server configuration. So if you could add the IP address to the event, it would be exactly what I was looking for. :)

**Comment by brotkrueml** [comment]
@cyMarvin Yes, would be possible, I think. Can you open a new issue for that? In the meantime, you can use `$GLOBALS['TYPO3_REQUEST']` and retrieve the normalized params.

**Comment by cyMarvin** [comment]
@brotkrueml Sure. Thanks for the hint! Didn't think about that.
