### ISSUE TITLE
Cleanup command not schedulable

### ISSUE THREAD

**Issue by RKlingler** [brotkrueml/typo3-form-rate-limit#10]
I would like to run the formratelimit:cleanupexpiredstorageentries command through the scheduler. However, as for now the command is defined to not be schedulable. Is there any particular reason for it?

I assume it would be a simple change to remove the `'schedulable' => false` configuration. And I think it would also be helpful to others, as setting up a scheduler task is usually a lot simpler than setting up a cron job.

**Comment by brotkrueml** [comment]
Hasn't tested it.
@RKlingler Have you removed the flag and works for you as scheduler run (for both, running in backend manually and with Cronjob)?

**Comment by RKlingler** [comment]
I tested it with the last TYPO3 11 LTS version and in TYPO3 13.4.0. Works flawlessly in both. I tested running it manually from the command line, manually through the scheduler, as well as through the scheduler run via cron job.

I created a PR for it: #11
