### ISSUE TITLE
Adding client IP address to RateLimitExceededEvent

### ISSUE THREAD

**Issue by cyMarvin** [brotkrueml/typo3-form-rate-limit#2]
I would like to use the RateLimitExceededEvent to gather client IP addresses that reach the configured limit multiple times, so I can easily blacklist them in my server configuration.
With this feature one could use this extension not "just" for rate limiting but for spam detection as well.

If you would like to have a logging feature inside this extension, I might create a PR when I'm done. Otherwise I will create an extension using the event.

**Comment by brotkrueml** [comment]
@cyMarvin For the logging feature I would suggest a custom solution, as this might not needed for every use case and the implementation might differ from installation to installation.

**Comment by brotkrueml** [comment]
Available in v1.3.0.
