### ISSUE TITLE
Maybe add a small comment 🙈 

### ISSUE THREAD

**Issue by SvenJuergens** [brotkrueml/typo3-form-rate-limit#9]
Hi @brotkrueml ,

First of all, thank you very much for the extension.
I used it as a basis to get an fast integration into the good old formhandler 🙈 😃 

I also integrated the event listener according to the instructions, but I only copied and pasted and didn't look too closely. That's why I had the line ‘services:’ twice afterwards. 

My mistake, no question. 
But maybe a mini small suggestion for improvement for the documentation. So that others don't do the same.
Perhaps you could integrate a comment similar to the example here?
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Events/EventDispatcher/Index.html#EventDispatcherRegistration

Many Thanks
Sven

**Comment by brotkrueml** [comment]
@SvenJuergens Oh, yes, thanks for the suggestion. Side note: I added that comment in the official docs some time ago to make it clearer to the reader ;-)
